version: "2"

services:
  db:
    image: 'mysql:5.5'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'typo3'
      MYSQL_PASSWORD: 'password'

  typo3:
    build: '.'
    environment:
      MYSQL_HOST: 'db'
      MYSQL_USER: 'typo3'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'typo3'
      INSTALL_TOOL_PASSWORD: 'password'
      XDEBUG_CONFIG: '${XDEBUG_CONFIG}'
    ports:
      - 8080:80
    links:
      - db
